server:
  port: 9300

caserver:
  host: 0.0.0.0
  port: 7054
  tls:
    enabled: true

cadb:
  host: 10.10.7.35
  port: 5432
  user: root
  password: baas123
  dbname: fabric_ca_zoo
  sslmode: disable

caadmin:
  user: admin
  pass: adminpw

caname: ca
cahome: cahome